# Generated by Django 4.2.16 on 2024-10-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_scanresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
