# Generated by Django 4.2.16 on 2024-10-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_scrapedlink11'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedLink',
        ),
    ]
