# Generated by Django 4.2.16 on 2024-10-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_gitleak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitLeak',
        ),
    ]
