# Generated by Django 4.2.16 on 2024-10-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_scrapedlink_delete_directoryenumresult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedlink',
            old_name='base_url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='scrapedlink',
            name='directory',
        ),
    ]
