# Generated by Django 4.2.16 on 2024-10-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_base_url_scrapedlink_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedLink',
        ),
    ]
