# Generated by Django 4.2.16 on 2024-10-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_scraplink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scraplink',
            new_name='Linkscrap',
        ),
    ]
