# Generated by Django 4.2.16 on 2024-10-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_scraplink_linkscrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('encrypted_value', models.TextField()),
                ('encryption_type', models.CharField(max_length=50)),
            ],
        ),
    ]
