# Generated by Django 4.2.16 on 2024-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_sitemapurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('found_link', models.URLField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
