# Generated by Django 4.2.16 on 2024-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_linkresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LinkCheckResult',
        ),
        migrations.DeleteModel(
            name='LinkResult',
        ),
    ]
