# Generated by Django 4.2.16 on 2024-10-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_scrapedlink_delete_linkcheckresult_delete_linkresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllLinkScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedLink',
        ),
    ]
