# Generated by Django 4.2.16 on 2024-10-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alllinkscrap_delete_scrapedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='AllLinkScrap',
        ),
    ]
