# Generated by Django 4.2.16 on 2024-10-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_delete_crawledlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HashResult',
        ),
    ]
