# Generated by Django 4.2.16 on 2024-10-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_gitscanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveDataFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('file_path', models.CharField(max_length=255)),
                ('strings_found', models.JSONField()),
                ('commit_id', models.CharField(max_length=100)),
                ('commit_author', models.CharField(max_length=255)),
                ('commit_date', models.DateTimeField()),
                ('commit_message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='GitScanResult',
        ),
    ]
