# Generated by Django 4.2.16 on 2024-10-31 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_sensitivedatafinding_delete_gitscanresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensitiveDataFinding',
        ),
    ]
