# Generated by Django 4.2.16 on 2024-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_delete_sensitivedatafinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('resource_url', models.URLField()),
            ],
        ),
    ]
