# Generated by Django 4.2.16 on 2024-11-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_scrapedresource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapedResource',
            new_name='LinkResource',
        ),
        migrations.RenameField(
            model_name='linkresource',
            old_name='resource_url',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='linkresource',
            old_name='source_url',
            new_name='url',
        ),
    ]
