# Generated by Django 4.2.16 on 2024-11-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_rename_scrapedresource_linkresource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('resource', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='LinkResource',
        ),
    ]
