# Generated by Django 4.2.16 on 2024-11-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_link_resource_delete_linkresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitDataLeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=255)),
                ('line_num', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
